source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.jimubox.com/app-labs/pintec-podspecs.git'

platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

def pods
end

target 'ApplepieDemo' do
    pods
end

target 'ApplepieDemoTests' do
    pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
