source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

target 'ApplepieDemo' do
    pod 'Applepie', :path => '../'
    pod 'DoraemonKit/WithLogger','3.0.1'
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    pod 'UMCAnalytics'
    pod 'UMCPush'
    pod 'UMCErrorCatch'
    pod 'UMCShare/UI'
    pod 'UMCShare/Social/ReducedWeChat'
    pod 'UMCShare/Social/ReducedQQ'
    pod 'UMCShare/Social/ReducedSina'
    pod 'UMCCommonLog'


    target 'ApplepieTests' do
      inherit! :search_paths
    end
    target 'ApplepieDemoTests' do
      inherit! :search_paths
    end
end
