source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

target 'Applepie' do
    pod 'Alamofire', '~> 4.7.3'
    pod 'ReactiveCocoa', '~> 8.0.2'
    pod 'CryptoSwift', '~> 0.13.0'
    pod 'PromiseKit', '~> 6.7.0'
    pod 'Kingfisher', '~> 4.10.1'
    pod 'PINCache', '~> 3.0.1-beta.7'
    pod 'Valet', '~> 3.2.2'
    pod 'DeviceKit', '~> 1.10.0'
    pod 'SwiftyUserDefaults', '~> 4.0.0-alpha.1'
    pod 'WebViewJavascriptBridge', '~> 6.0.0'
    pod 'CocoaLumberjack/Swift', '~> 3.4.2'
    pod 'SwiftLocation', '~> 3.2.3'
end

def pods
    pod 'Alamofire', '~> 4.7.3'
    pod 'ReactiveCocoa', '~> 8.0.2'
    pod 'CocoaLumberjack/Swift', '~> 3.4.2'
    pod 'SwiftLocation', '~> 3.2.3'
end

target 'ApplepieDemo' do
    pods
end

target 'ApplepieTests' do
    pods
end

target 'ApplepieDemoTests' do
    pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'ReactiveCocoa'
        config.build_settings['SWIFT_VERSION'] = '4'
        else
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
